from .abstract_datamodule import AbstractDataModule
from .cifar10datamodule import CIFAR10DataModule
from .mnistdatamodule import MNISTDataModule
from .random_datamodule import RandomNoiseDataModule
from .imagenet_latents_datamodule import ImageNetLatentsDataModule
